/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv';
import { Product, FastType } from './common.types';
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { Product, FastType };
export const Schema = {
  $id: './src/common.types.ts',
  $schema: 'http://json-schema.org/draft-07/schema#',
  definitions: {
    FastType: {
      type: ['string', 'number'],
    },
    Product: {
      defaultProperties: [],
      properties: {
        id: {
          type: 'number',
        },
        name: {
          type: 'string',
        },
        quantity: {
          type: 'number',
        },
        type: {
          enum: ['BOOK', 'FURNITURE'],
          type: 'string',
        },
      },
      required: ['id', 'name', 'quantity', 'type'],
      type: 'object',
    },
  },
};
ajv.addSchema(Schema, 'Schema');
export function validate(typeName: 'Product'): (value: unknown) => Product;
export function validate(typeName: 'FastType'): (value: unknown) => FastType;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(
        `No validator defined for Schema#/definitions/${typeName}`,
      );
    }

    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' +
          typeName +
          ': ' +
          ajv.errorsText(
            validator.errors!.filter((e: any) => e.keyword !== 'if'),
            { dataVar: typeName },
          ),
      );
    }

    return value as any;
  };
}
